trigger:
- main

pool:
  name: 'Raj-Agent-Pool'

stages:
  - stage: TerraformInstall
    jobs:
    -  job: TerraformInstall
       steps:
       
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/rajmaurya-devops-pipeline'
            backendServiceArm: 'raj-app-reg'
            backendAzureRmResourceGroupName: 'amit_rg'
            backendAzureRmStorageAccountName: 'amitstorage32345'
            backendAzureRmContainerName: 'amitcontainer'
            backendAzureRmKey: '''tf/terraform.tfstate'''

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'raj-app-reg'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'raj-app-reg'