trigger:
- main

pool:
  name: 'Raj-Agent-Pool'

stages:
- stage: TerraformInstall
  jobs:
  - job: TerraformInstall
    steps:

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rajmaurya-devops-pipeline'
        backendServiceArm: 'raj-app-reg'
        backendAzureRmResourceGroupName: 'raj_rg'
        backendAzureRmStorageAccountName: 'stgraj123'
        backendAzureRmContainerName: 'raj-container12'
        backendAzureRmKey: 'tf/terraform.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rajmaurya-devops-pipeline'
        environmentServiceNameAzureRM: 'raj-app-reg'

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rajmaurya-devops-pipeline'
        environmentServiceNameAzureRM: 'raj-app-reg'